### ISSUE TITLE
Disable notification

### ISSUE THREAD

**Issue by Egregius** [massdest/redmine_telegram_email#3]
Telegram has a option in their api to disable the notification sound. In other words: the message appears in the chat history but not on the welcome screen and didn't make a sound. That's great for logging purposes. 
The option is quite simple: disable_notification=true must be added to the post data.

In my opinion it would be great if users could select to disable the notification, or even better if they could select it depending on the priority. Something like if priority < 3 disable sound.

Good idea?

**Comment by massdest** [comment]
Yes, sounds good, but I dont think it very necessary, because common idea of plugin is get notifications on redmine issues with sound :) And I dont think that users need debug something or logging, in case email are just fine for logging, telegram more instant style. 

But if you want, just do it yourself and send PR to me, ruby very simple language, just make user custom field and simple logic like in other custom fields.

**Comment by Egregius** [comment]
I'll try it myself then ;)
